
- name: popolo_entity
  label: Popolo Entity
  obj: entity
  attributes:
    - name: identity
      label: Foreign system identifiers

- name: popolo_person
  label: Person
  obj: entity
  attributes:
    - name: given_name
      label: Given name
    - name: family_name
      label: Family name
    - name: gender
      label: Gender
    - name: honorific_prefix
      label: Honorific Prefix
    - name: popit_api_url
      label: PopIt API URL
      hidden: true
    - name: pa_api_url
      label: People's Assembly API URL
      hidden: true

- name: popolo_organization
  label: Organization
  obj: entity
  attributes: []

- name: details
  label: Generic Entity Details
  obj: entity
  hidden: true
  attributes:
    - name: website
      label: Website
    - name: email
      label: Email Address
    - name: telephone_number
      label: Telephone
    - name: fax_number
      label: Fax Number
    - name: postal_address
      label: Postal Address
    - name: physical_address
      label: Physical Address

- name: jse_company
  label: Company (JSE)
  obj: entity
  attributes:
    - name: jse_status
      label: Status at JSE
    - name: jse_registration_number
      label: Registration Number
    - name: jse_code
      label: Alphabetic Code
    - name: jse_role
      label: Role at JSE
    - name: jse_nature_business
      label: Nature of business

- name: jse_role
  label: Role at JSE
  obj: relation
  attributes:
    - name: role
      label: Role Description
