

- name: popolo_membership
  label: Membership
  obj: relation
  attributes:
    - name: role
      label: Role
    - name: start_date
      label: Start date
      datatype: datetime
    - name: end_date
      label: End date
      datatype: datetime

- name: popolo_area
  label: Geographic area
  obj: entity
  attributes:
    - name: area_classification
      label: Area classification

# Johannesburg Stock Exchange


- name: jse_role
  label: Role at JSE
  obj: relation
  attributes:
    - name: role
      label: Role Description

# Who's Who

# Education

- name: qualification
  label: Educational Qualification
  obj: entity
  attributes:
    - name: qualification_name
      label: Qualification Name
    - name: level
      label: Level
    - name: honorary
      label: Honorary

# Directorship and financial interests in PA

- name: pa_directorship
  label: Directorship
  obj: relation
  attributes:
   - name: report
     label: Source report

- name: pa_financial_interest
  label: Financial Interest
  obj: relation
  attributes:
   - name: report
     label: Source report
   - name: nature
     label: Nature of the interest
   - name: number
     label: Number of shares
   - name: nominal_value
     label: Nominal value
