
# Generic schemata

- name: details
  label: Generic Entity Details
  obj: entity
  hidden: true
  attributes:
    - name: website
      label: Website
    - name: email
      label: Email Address
    - name: telephone_number
      label: Telephone
    - name: fax_number
      label: Fax Number
    - name: postal_address
      label: Postal Address
    - name: physical_address
      label: Physical Address
    - name: summary
      label: Summary

- name: political_committee
  label: Committee
  obj: entity
  attributes: []

- name: political_party
  label: Party
  obj: entity
  attributes: []

# Popolo, PA Edition

- name: popolo_entity
  label: Popolo Entity
  hidden: true
  obj: entity
  attributes:
    - name: popit_id
      label: Foreign system identifiers
      hidden: true
    - name: pa_url
      label: People's Assembly URL

- name: popolo_person
  label: Person
  obj: entity
  attributes:
    - name: given_name
      label: Given name
    - name: family_name
      label: Family name
    - name: gender
      label: Gender
    - name: honorific_prefix
      label: Honorific Prefix
    - name: popit_api_url
      label: PopIt API URL
      hidden: true

- name: popolo_organization
  label: Popolo Organization
  obj: entity
  attributes:
    - name: org_category
      label: Category
    - name: org_classification
      label: Classification

- name: popolo_membership
  label: Membership
  obj: relation
  attributes:
    - name: role
      label: Role
    - name: start_date
      label: Start date
      datatype: datetime
    - name: end_date
      label: End date
      datatype: datetime

# Johannesburg Stock Exchange

- name: jse_company
  label: Listed Company
  obj: entity
  attributes:
    - name: jse_status
      label: Status at JSE
    - name: jse_registration_number
      label: Registration Number
    - name: jse_code
      label: Alphabetic Code
    - name: jse_role
      label: Role at JSE
    - name: jse_nature_business
      label: Nature of business

- name: jse_role
  label: Role at JSE
  obj: relation
  attributes:
    - name: role
      label: Role Description
